version: 2
updates:
  # Check for updates to GitHub Actions every month
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Prevent too many PRs from dependabot but keep major bumps as individual
    # PRs so breaking changes can be reviewed appropriately
    groups:
      gh-actions-minors-and-patches:
        update-types:
          - 'minor'
          - 'patch'
  # Check the npm registry for updates every month
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'weekly'
    # Prevent too many PRs from dependabot but keep major bumps as individual
    # PRs so breaking changes can be reviewed appropriately
    groups:
      npm-minors-and-patches:
        update-types:
          - 'minor'
          - 'patch'
    # Warnings started to appear in Next 14.0.2 in dev mode due to DREI.
    # https://github.com/vercel/next.js/issues/58557 Don't update to it and see
    # if the next version fixes it, along with the r3f-perf issue
    ignore:
      - dependency-name: 'next'
        versions: ['14.0.2', '14.0.3']
      - dependency-name: '@next/mdx'
        versions: ['14.0.2', '14.0.3']
      - dependency-name: 'eslint-config-next'
        versions: ['14.0.2', '14.0.3']
    # Because this is an application, the package.json can stay strict, so no
    # need to bump the lock file only
    # versioning-strategy: 'increase-if-necessary'
